rm(list=ls())
library(fields); library(maps); library(ncdf4);library(abind)
library(geosphere)
setwd("~/Documents")
source('Function/get_geo.R')
source('Function/get_met.R')
source('Function/read_met.R')
source('Function/read_method.R')

#===== define functions =====
setwd("~/Documents/CH4_Mexico/Figures/Figure 4")
met=read.csv("Table.csv")
met=as.matrix(met)

# dev.new(width=5,height=3.2)

pdf("/Users/lu/Documents/CH4_Mexico/Figures/Figure 4/Rplot.pdf",width=5,height=3.2)
par(mai=c(0.6, 0.8, 0.25, 0.8), mgp=c(1.2, 0.4, 0), tcl=-0.2, ps=11)
plot(met[,3]*100,met[,2]*100,axe=F,xlab="",ylab="",pch=16,ylim=c(0,70),col=1)
axis(1)
axis(2)
mtext("Percentage of emitted methane from oil industry (%)",side=1,line=1.5,col=1)
mtext("% of flaring from oil and gas",side=2,line=2.5,col=1)
mtext("in prior estimates",side=2,line=1.5,col=1)
text(x=82,y=55,"R6")
text(x=2,y=4,"R7")
box()
par(new=T)
plot(met[,3]*100,met[,8]*100,axe=F,xlab="",ylab="",pch=16,ylim=c(0,69),col=4)
axis(4,col=4,col.ticks=4,col.axis=4)
mtext("% of VIIRS estimated flaring",side=4,line=1.5,col=4)
mtext("in posterior estimates ",side=4,line=2.5,col=4)
title("Relationship of flaring methane with the oil industry",font.main=1,cex.main=1)
text(x=68,y=66,"Combustion efficiency = 97%",cex=0.7)
dev.off()